### ISSUE TITLE
Manage clustering behavior 

### ISSUE THREAD

**Issue by wandersage** [novalabio/react-native-maps-super-cluster#101]
Hello. I have a situation when I need to manage clustering. For ex, I have **few markers placed at the same point**. when I zoom it on over 13lvl - **cluster disappears** and I see 1 marker, because other markers is below as a stack, and I'm not able to choose them.  So I need that cluster doesn't disappears.
 **Is it any approaches or workarounds for this?** 
thanks.

**Comment by 39otrebla** [comment]
@wandersage did you try tweaking [radius and extent](https://github.com/novalabio/react-native-maps-super-cluster#props)? There's nothing we can do on the library side. You should implement custom logic for handling marker click when there are multiple markers on the same point, or modify your data in order to have just one marker that references multiple places.
