### ISSUE TITLE
Is it possible to add properties to cluster ?

### ISSUE THREAD

**Issue by aharon-vish** [novalabio/react-native-maps-super-cluster#124]
I need to know how to render cluster by type, 
Is it possible to make a different cluster (marker) style ?

**Comment by 39otrebla** [comment]
@aharon-vish If I got the point, you should be able to get clustered points (i.e. items into the cluster) using the `getLeaves()` method (see the example in the Readme) and then compute the cluster type from there.

It wouldn't make much sense to have a "type" for clusters because you don't know their content in advance.
