### ISSUE TITLE
Ghosting Markers/Clusters

### ISSUE THREAD

**Issue by mathewmorris** [novalabio/react-native-maps-super-cluster#47]
I'm having a strange ghost effect when my region changes. Instead of a spring effect in the source code. Sometimes it springs, but most times it will fade in/out. 

GIF Example:
![ghosting](https://user-images.githubusercontent.com/10860014/44279672-dec1f200-a217-11e8-9307-d7a7046c3b64.gif)

I don't have any animation packages/methods being imported into my project. So, I don't think the code will help. Right now, I have `animateClusters` turned off since I don't like the effect.

Have you experienced this as well?

**Comment by 39otrebla** [comment]
Not sure what could cause a different animation than expected. But I realise just now that would be way better to leave animation configuration up to the developer rather than having it "hardcoded" within the library.

Me and @leolusoli will release an update soon for letting developers customizing animation.

**Comment by mathewmorris** [comment]
@39otrebla awesome. I will also work on a PR to see if I can contribute 👍

**Comment by PurnimaNaik** [comment]
Still facing the ghost markers issue with `layoutAnimationConf` prop
