### ISSUE TITLE
Only cluster when there are more markers than a certain number.

### ISSUE THREAD

**Issue by bluenex** [novalabio/react-native-maps-super-cluster#55]
Is there a way to render a cluster only when the markers in radius are more than a certain number? I was finding for a prop like `minimumClusterSize` but can't find one.

I'm curious if this is possible with the SuperCluster. I have also checked the [mapbox/supercluster](https://github.com/mapbox/supercluster#options), but can't seem to find this.

However, I suspect the third argument of `getLeaves` here:

https://github.com/novalabio/react-native-maps-super-cluster/blob/2247261b3c24c9d76e40c09cc0c5aed8952b8fef/ClusteredMapView.js#L114

Does this method do what I think? If so I will try to create a PR.

**Comment by victormartingarcia** [comment]
Need a solution for this too...  now there's plenty of nonsense (2) clusters

**Comment by 39otrebla** [comment]
@victormartingarcia I believe this is not in our domain and SuperCluster seems to have no option for this.

The only thing I can think of for solving your problem is to tweak  [`extent` prop](https://github.com/novalabio/react-native-maps-super-cluster#props) (i.e. tile size). By decreasing that number your are telling SuperCluster to NOT clusterize points if their distance (in pixels) is less than `extent`.

We could also filter/map/reduce within our library, right after receiving the clusterization result, but we believe it would have a considerable impact on performance.
