### ISSUE TITLE
Can the Markers of a ClusteredMapView be accessed through their refs?

### ISSUE THREAD

**Issue by Traningsoverall** [novalabio/react-native-maps-super-cluster#8]
I'm trying to access the Mapview.Markers (created in the renderMarker-function) of a ClusteredMapView through their refs. 

`renderMarker = (mapObject) => {
        return (
            <Marker
                ref={mapObject.Id}
                key={mapObject.Id}
                coordinate={mapObject.position}
                image={this.renderMarkerImage(mapObject)}
                >
                    <MapView.Callout style={styles.callout}>
                        {this.renderCallout(mapObject)}
                    </MapView.Callout>
                </Marker>
            )
        }`

This is to programatically call their showCallout-method. I can access the clusteredMapView itself through its ref, but when I try this, nothing.
`deviceLog.log(this.refs.clusteredMapView.refs) // {} (an empty object)`
`deviceLog.log(this.refs.clusteredMapView.getMapRef().refs) // {} (an empty object)`

Any suggestions or is this not even possible with the ClusteredMapView?

**Comment by 39otrebla** [comment]
First of all. you are using `ref` prop in the wrong way, and `<component>.refs` is wrong as well as it has been deprecated. Now `ref` prop takes a function that gets called with the reference to the component as parameter. [Here is the doc](https://reactjs.org/docs/refs-and-the-dom.html), and here is a non-exhaustive usage example:

```
<Marker
  key={mapObject.Id} 
  ref={(r) => { this.markers[mapObject.id] = r }}
  [...] />
```

Bear in mind that I used `this.markers` as an object because you need references to multiple child components, but usually you would just do something like `(r) => { this.mySingleComponent = r }`.

**Comment by Traningsoverall** [comment]
Many thanks @39otrebla for a friendly and educational answer!
Really liking the ClusteredMap so far.
